### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by chrisbyrne** [oblador/angular-lazytube#1]
When building a project, angular-lazytube.js gets replaced with lazytube.min.js which cannot be found and therefore breaks the build. 

I believe this is an issue with your bower.json, specifically line 4 which specifies 'lazytube.min.js' and not 'angular-lazytube.min.js'

**Comment by oblador** [comment]
Hi @chrisbyrne,

Check out the [0.1.1 release](https://github.com/oblador/angular-lazytube/releases/tag/v0.1.1) and see if that solves your problem!
